### ISSUE TITLE
Breaks craft-from-container mechanic or UI (at least from Valheim Plus)

### ISSUE THREAD

**Issue by VulcanTourist** [BruceOfTheBow/BruceComfyMods#2]
After installing this mod, the crafting UI was displaying ZERO availability of every material input stored in containers.  It may have been that crafting was still possible to the extent that actual amounts were available and accessible in spite of reporting nothing, but blindly crafting quantities of anything is not a desirable workaround to the blindness.  That information is crucial, not optional.

The addition to the crafting UI of a quantity selection was also broken and nonfunctional, refusing to increment past 1.

**Comment by stelucz** [comment]
confirming

**Comment by BruceOfTheBow** [comment]
Craft-from-containers is not an approved mod on our server so I will not be adding explicit support for this. Craft-from-containers mod is welcome to hook in and modify the inventory search to expand to nearby chests to support their mod. Disabling of the increment/decrement button when closing the UI on the upgrade tab then reopening will be fixed with the update released today.
